// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Formplug","status":true,"description":"Allows users to give a thumbs up, down or Wiggle to Formbar and interact with Formbar API via socket.io-client.","parameters":{"Formbar URL":"https://formbeta.yorktechapps.com/","API Key":"c30fb8c1041efc2b402992892fe643e16ef80b43298cb88c1ce63a1f0918398b8acd279d4c00eb4d970fea8fb004ee29da9ce128b0a38fbbca1e39ac12932076"}}
];
